### ISSUE TITLE
Race condition (Possibly) issue

### ISSUE THREAD

**Issue by killmeplz** [bitnami/bitnami-docker-postgresql#100]
**Steps to reproduce the issue:**

```
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=test
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=test
```
docker-compose up -d

**Describe the results you received:**

During first run:
```
postgre TRACE [runProgram] Executing: /opt/bitnami/postgresql/bin/psql -U,postgres,-h,127.0.0.1,-c,CREATE DATABASE "test";
Error executing 'postInstallation': psql: FATAL:  the database system is starting up

```

**Additional information you deem important:**

It happens occasionally, in about 5% cases, so I guess it could happen because of the long db starting process i.e. regular race condition. Am I right?
