### ISSUE TITLE
Bitnami Posgresql master instance not showing with docker ps

### ISSUE THREAD

**Issue by AndreasKralj** [bitnami/bitnami-docker-postgresql#115]
**Description**

I'm trying to use the Posgresql configuration from the tutorial [here](https://hub.docker.com/r/bitnami/postgresql/), and I copied the docker-compose.yml contents from the tutorial to my local file in the directory temp2. When I run `docker-compose up -d`, Docker reports that both the slave and master come up, but only the slave shows up when I execute `docker ps`. I tried to expose the port 5432 and check to see if it was listening, but it was not listening on my local machine.

**Steps to reproduce the issue:**

1. Copy the docker-compose.yml contents into a local directory, mine was named temp2. The contents are as follows:

```
version: '2'

services:
  postgresql-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432'
    volumes:
      - 'postgresql_master_data:/bitnami'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
    volumes:
      - './bitnami:/bitnami'
  postgresql-slave:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
```

2. Start the docker instances with `docker-compose up -d`. You should see the following output, if it's the first time you're downloading it you should also see the images being downloaded:

```
Creating network "temp2_default" with the default driver
Creating temp2_postgresql-master_1 ... 
Creating temp2_postgresql-master_1 ... done
Creating temp2_postgresql-slave_1 ... 
Creating temp2_postgresql-slave_1 ... done
```

3. Run `docker-compose ps` to show the instances. Only the slave will appear as follows:

```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                     NAMES
3c2541129144        bitnami/postgresql:latest   "/app-entrypoint.sh …"   6 seconds ago       Up 3 seconds        0.0.0.0:32783->5432/tcp   temp2_postgresql-slave_1
```

**Describe the results you received:**

I only saw the slave insance.

**Describe the results you expected:**

I expected to see and to be able to interact with the master.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.1
 Git commit:        e68fc7a
 Built:             Fri Jan 25 14:33:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       e68fc7a
  Built:            Thu Jan 24 10:49:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 33
 Running: 0
 Paused: 0
 Stopped: 33
Images: 167
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.749GiB
Name: AndreaskraljDev
ID: DOMH:6EAA:FJGT:XJNX:GORA:RMHR:PQGX:DHLA:WQXO:JH6E:6MUB:YTA6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I am running this on a physical Ubuntu 18.04 instance.

**Comment by javsalgar** [comment]
Hi,

Could you execute docker-compose -a to see if the container is there? If so, could you execute docker logs on the container afterwards?

**Comment by AndreasKralj** [comment]
Unfortunately, `docker-compose -a` was not recognized as a valid command on my machine. I ran `docker-compose ps` and got the following output:

```
         Name                   Command           State            Ports        
--------------------------------------------------------------------------------
temp2_postgresql-        /app-entrypoint.sh       Exit 1                        
master_1                 /run.sh                                                
temp2_postgresql-        /app-entrypoint.sh       Up       0.0.0.0:32770->5432/t
slave2_1                 /run.sh                           cp                   
temp2_postgresql-        /app-entrypoint.sh       Up       0.0.0.0:32769->5432/t
slave_1                  /run.sh                           cp  
```

Trying to get the logs failed on the master, as I got the following error:

```
docker-compose logs temp2_postgresql-master1
ERROR: No such service: temp2_postgresql-master1
```

**Comment by javsalgar** [comment]
Hi,

Could you try this command? 

```
docker logs temp2_postgresql-master_1
```

**Comment by AndreasKralj** [comment]
Hi,

Thank you so much for that! I was able to find that I didn't have the /bitnami/postgresql directory, so I was able to create it and everything worked! The log output is below:

```
Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql'

Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> postgresql.conf file found...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql'
```

Sorry I didn't notice that before, thank you so much for the help!

**Comment by AndreasKralj** [comment]
Hi,

Thank you so much for that! I was able to find that I didn't have the /bitnami/postgresql directory, so I was able to create it and everything worked! The log output is below:

```
Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql'

Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> postgresql.conf file found...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql'
```

Sorry I didn't notice that before, thank you so much for the help!

**Comment by AndreasKralj** [comment]
Unfortunately it looks like the master errors out still. The issue is that /bitnami/postgresql cant' be created on the Docker container, not on my local machine like I had previously thought.

**Comment by AndreasKralj** [comment]
It was a UID issue. I changed the UID of the bitnami folder to 1001 and it worked. My docker-compose.yml file has this container which was inspired from [here](https://github.com/bitnami/bitnami-docker-mariadb/issues/136):

```
  fix-postgresql-permissions:
    image: 'bitnami/postgresql:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ./bitnami:/bitnami
```
