### ISSUE TITLE
Can't Use Both a Custom Config and User Environment Variables

### ISSUE THREAD

**Issue by ewalkup** [bitnami/bitnami-docker-postgresql#121]
**Description**
You can't use both a custom postgresql.conf file AND any user/db creation environment variables

I want to deploy a simple master-slave pair using the replication options, as well as give it my own custom postgresql.conf file. If I try and give it a config file, it will not create the replication user, the database, or any user specified under POSTGRESQL_USERNAME. If I remove the custom file from the equation, it will create all the users/db as expected. Is there a way to do both via the arguments without having to resort to writing my own sql setup files?

**Steps to reproduce the issue:**

1. Write a basic docker-compose YAML file for the master and the slave. My master file:
```
version: '3'
services:
  database:
    image: bitnami/postgresql:11-debian-9
    restart: always
    ports:
      - '0.0.0.0:5432:5432'
    environment:
        - POSTGRESQL_PASSWORD=testpassword
        - POSTGRESQL_USERNAME=testuser
        - POSTGRESQL_DATABASE=testdb
        - POSTGRESQL_REPLICATION_MODE=master
        - POSTGRESQL_REPLICATION_USER=repuser
        - POSTGRESQL_REPLICATION_PASSWORD=reppassword
    volumes:
     - /data/postgres/config:/bitnami/postgresql/conf # a custom postgresql.conf is in here
```
2. Bring the master and slave up using `docker-compose up -d`
3. Go into the container via bash
4. Use psql in /opt/bitnami/postgresql/bin to get into the db with `pgsql -U postgres`
5. Run `\l` to list databases, see that testdb was not created and only the default postgres ones are present
6. Run `\du` and see that neither testuser or repuser was created - the only user is postgres

**Describe the results you received:**
The custom config is applied, but neither of the users nor the database specified via the environment variables are created. The slave fails to connect with repuser since it does not exist

**Describe the results you expected:**
I expected both the custom config to be used AND the users and database to be created, since the data directory is empty and reinitialized on every run. I tested that this issue is also present if I used a permanent storage volume that I cleared after every run.

**Additional information you deem important (e.g. issue happens only occasionally):**

You can verify that is it the presence of the config file that makes the users/db not be created by either:
* moving the config file out of the mounted volume and re-running
* Removing the volume entirely from the YAML file

In both cases, the users and db will be created as expected, though obviously now there is no custom config applied.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54266
 Built:             Wed Mar 27 18:35:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.09.4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-46-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.7GiB
Name: redacted
ID: 335Y:7AHR:A7XG:DCVB:AWMB:VI2I:LI35:ROI6:5DC4:BU44:WF6B:Z462
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Using the 11-debian-9 image running on an Ubuntu 18.04 base.

**Comment by miguelaeh** [comment]
Hi @ewalkup ,
I have followed your steps using your `docker-compose.yml` and a configuration file but in my case the database and users are created properly.
```
postgres=# \l
                             List of databases
   Name    |  Owner   | Encoding | Collate | Ctype |   Access privileges
-----------+----------+----------+---------+-------+-----------------------
 postgres  | postgres | UTF8     | C       | C     |
 template0 | postgres | UTF8     | C       | C     | =c/postgres          +
           |          |          |         |       | postgres=CTc/postgres
 template1 | postgres | UTF8     | C       | C     | =c/postgres          +
           |          |          |         |       | postgres=CTc/postgres
 testdb    | postgres | UTF8     | C       | C     | =Tc/postgres         +
           |          |          |         |       | postgres=CTc/postgres+
           |          |          |         |       | testuser=CTc/postgres
(4 rows)
```

Also, I test it with the following `docker-compose` and It works properly too:
```
version: '2'
services:
  postgresql-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432'
    volumes:
      - 'postgresql_master_data:/bitnami'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
    volumes:
      - './config:/bitnami/postgresql/conf'
  postgresql-slave:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432                                                                                                                     
```
Have in mind that If the environment vars affect to the configuration file, they will not apply if a configuration file is provided, in other case, they will be applied.
