### ISSUE TITLE
Using pl_PL.UTF-8 locale in helm chart

### ISSUE THREAD

**Issue by loockass** [bitnami/bitnami-docker-postgresql#127]
Hello

Is it possible to use pl_PL.UTF-8 locale while deploying on kubernetes with helm chart without changing docker image?

**Comment by javsalgar** [comment]
Hi,

Could you confirm that it worked by changing the `LC_` environment variables in the docker-compose? If so, then we could add a feature in the chart to include these env vars.

**Comment by loockass** [comment]
Hello, I've run container using following docker-compose.yml:
```yml
version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - LANG=pl_PL.UTF-8
      - LANGUAGE=pl_PL
      - LC_CTYPE=pl_PL.UTF-8
      - LC_NUMERIC=pl_PL.UTF-8
      - LC_TIME=pl_PL.UTF-8
      - LC_COLLATE="pl_PL.UTF-8"
      - LC_MONETARY=pl_PL.UTF-8
      - LC_MESSAGES="pl_PL.UTF-8"
      - LC_PAPER=pl_PL.UTF-8
      - LC_NAME=pl_PL.UTF-8
      - LC_ADDRESS=pl_PL.UTF-8
      - LC_TELEPHONE=pl_PL.UTF-8
      - LC_MEASUREMENT=pl_PL.UTF-8
      - LC_IDENTIFICATION=pl_PL.UTF-8
      - LC_ALL=
```

```
➜  ~ sudo docker exec -it lsabiniok_postgresql_1 locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=pl_PL.UTF-8
LANGUAGE=pl_PL
LC_CTYPE=pl_PL.UTF-8
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE=\"pl_PL.UTF-8\"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES=\"pl_PL.UTF-8\"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```
But unfortunatelly collation doesn't work as I expect.
