### ISSUE TITLE
Volume mount `/bitnami` does not longer work

### ISSUE THREAD

**Issue by wochinge** [bitnami/bitnami-docker-postgresql#141]
Image Tag: 11.2.0

Docker-Compose file:
```
services:
 db:
    image: "bitnami/postgresql:11.2.0"
    volumes:
    - ./db:/bitnami
```

**Expected**: All data should be in the host directory `db`.

**Actual**: No data is in the host directory `db`. The container writes them in `/bitnami/postgresql` but that directory is not mounted. I assume thats cause of 

https://github.com/bitnami/bitnami-docker-postgresql/blob/1f02bae481b53ea42eaff2d93f3331325d011af8/11/debian-9/Dockerfile#L26

```
VOLUME [ "/bitnami/postgresql", "/docker-entrypoint-initdb.d" ]
```

So if I mount `./db/:/bitnami/postgresql`, it works.

Solutions imho: 
- either fix this in the Dockerfile 
- or update the Readme

**Comment by miguelaeh** [comment]
Hi @wochinge ,
I am facing the same issue. In any case you can use it by the moment mounting a directory into `/bitnami/postgresql` having the right permissions on your computer.
I have tested it on other computer with other version of Docker and this does not happen. I am going to try to investigate the issue.
Thank you for reporting.

**Comment by sicksid** [comment]
same for me, it does not work specially if i use a volume like this

`
volumes:
  pg_data: {}
`

**Comment by miguelaeh** [comment]
Hi @sicksid ,
We realized this is a bug due to the recent migration of the container from node.js to bash.
Thank you very much for reporting.
We are trying to fix it. In the mean time if you are interested on mount volumes at `/bitnami` you can use this version of the image: `bitnami/postgresql:10.7.0-r67`. I have tested it and it works fine.

**Comment by miguelaeh** [comment]
Hi again @sicksid ,
We know the reason of that. It is not a bash problem as I thought.
The problem here is that the Dockerfile is mounting as mount point `/bitnami/postgresql` and when you mount a volume on `/bitnami` this volume wraps up the first but is a new volume so data is lost.
Just mount the volume on `/bitnami/postgresql`.

**Comment by sicksid** [comment]
thanks! mounting to /bitnami/postgresql works!

**Comment by wochinge** [comment]
Sorry, I thought both, problem and potential solutions, were already described properly in the issue

**Comment by jonovate** [comment]
This is beyond aweful impact guys and needs much better communication.

I trust Bitnami to have latest patches/OS updates - so if I do a `docker-compose pull` and then a `docker-compose up -d` -- I shouldn't have to fear that I just lost my DB because the volume changed on a minor .11 to .12.

**Comment by beltran-rubo** [comment]
Hi @jonovate, we are sorry about that. Definitely is not the user experience that we are looking for.

It was a configuration issue on our side and that should not happen in the future. For minor versions we work on maintaining the compatibility with previous versions and warn users in the logs or in the README if that is not the case. We will implement the mechanisms to avoid this error for upcoming versions. We are already working on using immutable tags for Helm Charts and we will revisit if we should also use a similar approach for docker-compose.

**Comment by sicksid** [comment]
still having problems even after changing the mounting to be /bitnami/posqtgresql
on version postgresql:10.7.0-r67 and postgresql:11 and postgresql:9.6

**Comment by miguelaeh** [comment]
Could you describe the problems please?

**Comment by sicksid** [comment]
i run all my images using `docker-compose up`

this is for postgresql:9.6

![image](https://user-images.githubusercontent.com/7379966/58341849-d20ca300-7e14-11e9-9c4d-6776c83838fe.png)


this is postgres:10.7
![image](https://user-images.githubusercontent.com/7379966/58342028-45aeb000-7e15-11e9-8621-e4cd379167b3.png)

this is postgres:latest

![image](https://user-images.githubusercontent.com/7379966/58342076-5fe88e00-7e15-11e9-9ba5-fca21f1d9618.png)

**Comment by miguelaeh** [comment]
I am not able to reproduce that, could you try to remove the volumes to force the configuration stage to run again and create the configuration file?
Use `docker-compose down -v` and then `docker-compose up`

**Comment by BienTrinh** [comment]
This is my docker-compose.yml

```
version: '3.1'
services:
  postgresql-master:
    image: 'bitnami/postgresql:11'
    ports:
      - '5432'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=change_me
      - POSTGRESQL_USERNAME=tv
      - POSTGRESQL_PASSWORD=change me
      - POSTGRESQL_DATABASE=tv_api
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - /data01/postgres:/bitnami/postgresql
    network_mode: 'host'
    container_name: "postgres-master"
```
then execute command below:
`#chmod 777 -R /data01/postgres && docker-compose -f docker-compose up -d
` you will have every things you need persis file to local dir.

**Comment by sicksid** [comment]
guys i keep having problems booting up other images, here is part of my config

```
  db:
    image: bitnami/postgresql:9.6
    ports:
      - 5432
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER:-postgres}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE:-postgres}
    volumes:
      - pgdata_folder:/bitnami/postgresql
volumes:
  pgdata_folder:
```
this is what i get
![image](https://user-images.githubusercontent.com/7379966/59124285-eaa4af00-8924-11e9-9104-dd91499fa8d0.png)

however if i use `bitnami/postgresql:10.7.0-r67` everything works properly, i dont want to use a local folder that i need to set up, i wanted to keep using pgdata_folder and declare it inside volumes in docker-compose
