### ISSUE TITLE
Set fsync flag from environment variable

### ISSUE THREAD

**Issue by drieshooghe** [bitnami/bitnami-docker-postgresql#144]
**Description**

I'm trying to get the bitnami/postgres:11 image to run through docker-compose with the `fsync` configuration setting set to `off`.
There’s no need for fsync in most testing environments and disabling it would mean a significant speed improvement. 

If this option were available through an environment variable it would be very easy to use this image in CI pipelines.

**Comment by juan131** [comment]
Hi @drieshooghe 

You can mount your own `postgresql.conf` configuration file as described in the link below:

https://github.com/bitnami/bitnami-docker-postgresql#configuration-file

Or, if you prefer, you can extend the configuration as explained below:

https://github.com/bitnami/bitnami-docker-postgresql#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf

This way you can set `fsync` configuration setting set to `off`.

**Comment by drieshooghe** [comment]
Hi @juan131 

I saw that, thanks. But I was wondering if it wouldn't be useful to set it without overriding the configuration manually. In certain pipeline configurations you can't mount volumes, you can only specify the image and environment variables.

Like this for example:

```
image: node:10.15.0

pipelines:
  ...
          services:
            - postgres

definitions: 
  services: 
    postgres: 
      image: bitnami/postgresql:11
      variables:
        POSTGRES_DB: ... 
        POSTGRES_USER: ...
        POSTGRES_PASSWORD: ...
        POSTGRES_FSYNC: "off"
```
