### ISSUE TITLE
Waiting for replication master to accept connections

### ISSUE THREAD

**Issue by tintranvan** [bitnami/bitnami-docker-postgresql#164]
I have run docker-compose for master-container and slave-container in two docker-servers.

- In Master-Server:

```yaml
version: '2'
   services:
   postgresql-master:
    image: "bitnami/postgresql:9.6-centos-7"
    ports:
      - "5432:5432"
    volumes:
      - "/tmp/pg-master-data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
```

- In Slave-Server:

```yaml
version: '2'
services:
  postgresql-slave:
    image: 'bitnami/postgresql:9.6-centos-7'
    ports:
      - '5432:5432'
    volumes:
      - '/tmp/pg-slave-data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST='192.168.77.156'
      - POSTGRESQL_PASSWORD=my_password
     -  POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
```

---------------------------------------------------------------------------

Master-Container already run in Master-Server:

```bash
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                    NAMES
d2e1e307e9b7        bitnami/postgresql:9.6-centos-7   "/entrypoint.sh /run…"   24 minutes ago      Up 23 minutes       0.0.0.0:5432->5432/tcp   pgmaster_postgresql-master_1
```

**But i got the error when building Slave-Container, the network connection from Master-Server and Slave-Server is not the reason.**

```
INFO  ==> Waiting for replication master to accept connections (60 timeout)...
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
'192.168.77.156':5432 - no attempt
ERROR ==> PostgreSQL master is not ready after 60 seconds
INFO  ==> Stopping PostgreSQL...
```

Please help me

Thanks and Best Regards,
