### ISSUE TITLE
Data not persisted

### ISSUE THREAD

**Issue by peterlauri** [bitnami/bitnami-docker-postgresql#168]
**Description**

When restarting kubernetes deployment, data is not persisted even that persistent volume is mounted on /bitnami directory.

**Steps to reproduce the issue:**

1. Create a k8s deployment similar to this:

```
apiVersion: v1
kind: Service
metadata:
  name: postgres-main-master
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-main-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-main-master-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-main-master
spec:
  selector:
    matchLabels:
      app: postgres-main-master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-main-master
    spec:
      containers:
      - image: bitnami/postgresql:10.10.0-r55
        name: postgres-main-master
        resources:
          limits:
            memory: 2Gi
            cpu: '1.0'
        env:
        - name: POSTGRESQL_DATABASE
          value: spine
        - name: POSTGRESQL_USERNAME
          value: spine
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: POSTGRESQL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: POSTGRESQL_REPLICATION_MODE
          value: master
        - name: POSTGRESQL_REPLICATION_USER
          value: spinereplication
        - name: POSTGRESQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-main-master-persistent-storage
          mountPath: /bitnami
        - name: config-volume
          mountPath: /docker-entrypoint-initdb.d/my_init_script.sh
          subPath: my_init_script.sh
      volumes:
      - name: postgres-main-master-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-main-master-pv-claim
      - name: config-volume
        configMap:
          name: postgres-config
```

2. create a table and insert data
3. change the configuration and give cpu=2.0, and apply using kubectl
4. this will cause pod to stop and be recreated

**Describe the results you received:**

After new pod is launched, the table and data created in step 2 above is no longer there.

**Describe the results you expected:**

As I have a persistent volume mounted at /bitnami, I expect data to be there.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by andresbono** [comment]
Hi @peterlauri, I can't see the source of your issue, in theory, it should work. Could you please check that the volume is properly mounted in the container? You can execute the following command:
```
kubectl exec -it NAME_OF_YOUR_POD -- df -h
```

Does the volume appear mounted into the container?

**Comment by peterlauri** [comment]
@andresbono hi. Because we couldn't find a solution to this at that time, we decided to deploy the database on Google Cloud SQL instead. I will however make another attempt later on, will update the issue after that.

**Comment by peterlauri** [comment]
@andresbono yes, I did check that it was mounted...

**Comment by andresbono** [comment]
Hi @peterlauri, thanks for checking. We could reproduce your issue. The problem seems to be the path you are using to mount the volume that persists data:

```yaml
        volumeMounts:
        - name: postgres-main-master-persistent-storage
          mountPath: /bitnami
```

Instead of using `/bitnami`, you should use the path specified in the Dockerfile `/bitnami/postgresql`:

https://github.com/bitnami/bitnami-docker-postgresql/blob/0bedf1dfaba0b502738080a120b0c63c164d01e4/10/debian-9/Dockerfile#L26

Can you confirm it works for you that way?
