### ISSUE TITLE
Restarting a K8s pod fails with permission error of the data directory

### ISSUE THREAD

**Issue by hodossy** [bitnami/bitnami-docker-postgresql#176]
**Description**

Postgres cannot start as the permissions are not correct. This happens after the pod is killed. I have only found issues similar to this when deploying through a Helm chart.

```
postgresql 11:22:31.13 
postgresql 11:22:31.13 Welcome to the Bitnami postgresql container
postgresql 11:22:31.14 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 11:22:31.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 11:22:31.14 Send us your feedback at containers@bitnami.com
postgresql 11:22:31.14 
postgresql 11:22:31.15 INFO  ==> ** Starting PostgreSQL setup **
postgresql 11:22:31.18 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 11:22:31.18 INFO  ==> Loading custom pre-init scripts...
postgresql 11:22:31.18 INFO  ==> Initializing PostgreSQL database...
postgresql 11:22:31.19 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 11:22:31.20 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 11:22:31.20 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 11:22:31.20 INFO  ==> Configuring replication parameters
postgresql 11:22:31.21 INFO  ==> Configuring fsync
postgresql 11:22:31.22 INFO  ==> Loading custom scripts...
postgresql 11:22:31.22 INFO  ==> Enabling remote connections
postgresql 11:22:31.23 INFO  ==> Stopping PostgreSQL...
postgresql 11:22:31.23 INFO  ==> ** PostgreSQL setup finished! **
postgresql 11:22:31.26 INFO  ==> ** Starting PostgreSQL **
2019-11-08 11:22:31.271 GMT [1] FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
2019-11-08 11:22:31.271 GMT [1] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```

**Steps to reproduce the issue:**

1. Deploy a Stateful Set:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: <whatever you have>
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      role: database
  serviceName: app-db
  template:
    metadata:
      labels:
        app: my-app
        role: database
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql:11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-backend-config
              key: POSTGRES_DATABASE
        - name: POSTGRESQL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-backend-config
              key: POSTGRES_USERNAME
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-backend-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRESQL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-admin-credentials
              key: POSTGRES_ADMIN_PASSWORD
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: postgredb
          subPath: data
      securityContext:
        fsGroup: 1001
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: db-pvc
```
2. Wait untils it is successfully started
3. Kill the db pod:
`kubectl delete pods -l role=database`

**Describe the results you received:**

Pod recreated by the controller, but failed to start with `Back-off restarting failed container`. The logs are as above.

**Describe the results you expected:**

Pod successfully recreated.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Container Runtime Version:  docker://18.6.1

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

AWS EKS is used

If I scale down the Stateful Set to 0 and delete and recreate the PVC, then I can successfully scale up the deployment back to 1.

**Comment by juan131** [comment]
Hi @hodossy 

[The PostgreSQL Helm chart](https://github.com/helm/charts/tree/master/stable/postgresql) offers you a parameter (`volumePermissions.enabled`) that will allow you to add a **initContainer** to your **statefulset** definition which adapts the permissions in the attached volume.

Could you please ensure you're running the latest version of the chart and you enabled that option?

```console
$ helm repo update
$ helm install stable/postgresql --name my-release --set volumePermissions.enabled=true
```

**Comment by hodossy** [comment]
Hello,

I am not using the Helm chart. I will check what that option does in the charts.

**Comment by juan131** [comment]
As an alternative to the Helm chart, you can always use:

```
$ helm template stable/postgresql --name my-release --set volumePermissions.enabled=true > templates.yaml
```

Then you can take a look to the **templates.yaml** so you can inspect what K8s object are created and install them manually.

**Comment by hodossy** [comment]
I missed the initContainer :). Thank you very much and sorry for the late answer!

**Comment by sunlianqiang** [comment]
same issue, but in harbor helm. change the initContainer command also works.
add this line
>chmod 700 /var/lib/postgresql/data
```
initContainers:
      - name: "change-permission-of-directory"
        image: {{ .Values.database.internal.initContainerImage.repository }}:{{ .Values.database.internal.initContainerImage.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            chown -R 999:999 /var/lib/postgresql/data
            chmod 700 /var/lib/postgresql/data
```
