### ISSUE TITLE
SQLSTATE[08006] [7] FATAL: password authentication failed for user

### ISSUE THREAD

**Issue by DomKrulak** [bitnami/bitnami-docker-postgresql#177]
**Description**

I've packed all required images _( no need to mention them here )_ into my `docker-compose.yml` file to run my PHP application but it couldn't connect the user into database because of a wrong password or user doesn't exist. I think it's the second. And maybe database doesn't exist.

**Steps to reproduce the issue:**

1. Place the copy of `BITNAMI_IMAGE_VERSION="12.0.0-debian-9-r22"`  into computer
3. Pack the image into `docker-compose.yml` file
4. and `docker-compose up`

**Describe the results you received:**

The respond was `SQLSTATE[08006] [7] FATAL: password authentication failed for user`. 

Than I played around for a while and striped down unnecessary packages to run just PostgreSQL with PGadmin client and connect to database using credentials defined in `docker-compose.yml` file. 

The postgresql's respond in my CLI is:
`FATAL:  password authentication failed for user "project"`
`DETAIL:  Role "project" does not exist.`
`Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"`

I was following the documentation and I hope I understand it well.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here is my `docker-compose.yml` file

```
version: "3.7"
services:

  postgresql:
    build: ./docker/postgresql/12
    image: postgresql:12
    container_name: postgresql
    networks:
     - backend
   ports:
      - 5432
    volumes:
      - ./storage/postgresql:/bitnami/postgresql
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: secret
      POSTGRESQL_USERNAME: project
      POSTGRESQL_PASSWORD: project
      POSTGRESQL_DATABASE: project
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - backend
    ports:
      - 5555:80
    depends_on:
      - postgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: unless-stopped

networks:
  backend:
    external: true

volumes:
  postgresql:
```

**Version**

- Output of `docker version`: 

```
2.1.0.4 (39773)
```

- Output of `docker info`:

```
Engine: 19.03.4
```

- Output of `docker-compose version` (if applicable):

```
Compose: 1.24.1
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker for MAC
