### ISSUE TITLE
ALLOW_EMPTY_PASSWORD=yes Required for Slave Replica 

### ISSUE THREAD

**Issue by ewalkup** [bitnami/bitnami-docker-postgresql#189]
I am unsure if this is a bug or a documentation update that is needed.

**Description**

I have a simple master-slave (one replica) setup. According to the documentation (and according to a setup I've done before on earlier versions), there is no need to supply the `POSTGRESQL_PASSWORD` environment variable on the slave. I am working with an upgraded setup, and apparently this is no longer the case?

**Steps to reproduce the issue:**

1. Setup a basic postgres master
2. Setup a basic slave - my docker-compose file is:
```
version: '3'
services:
  database:
    image: bitnami/postgresql:11-debian-9
    restart: on-failure:20
    ports:
      - '0.0.0.0:5432:5432'
    environment:
        - POSTGRESQL_REPLICATION_MODE=slave
        - POSTGRESQL_MASTER_HOST=<host>
        - POSTGRESQL_REPLICATION_USER=<user>
        - POSTGRESQL_REPLICATION_PASSWORD=<password>
        - BITNAMI_DEBUG=true
    volumes:
        - /data/postgres/data:/bitnami/postgresql/data
        - /data/postgres/config:/bitnami/postgresql/conf
        - /var/log/postgresql:/opt/bitnami/postgresql/logs
    logging:
       driver: "json-file"
       options:
         max-size: "50m"
```
3. Try to run the slave with `docker-compose up`

**Describe the results you received:**

The container fails to start - the logs seen are:
```
Recreating root_database_1 ... done
Attaching to root_database_1
database_1  | postgresql 18:58:05.53 
database_1  | postgresql 18:58:05.53 Welcome to the Bitnami postgresql container
database_1  | postgresql 18:58:05.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
database_1  | postgresql 18:58:05.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
database_1  | postgresql 18:58:05.54 Send us your feedback at containers@bitnami.com
database_1  | postgresql 18:58:05.54 
database_1  | postgresql 18:58:05.55 DEBUG ==> Configuring libnss_wrapper...
database_1  | postgresql 18:58:05.56 INFO  ==> ** Starting PostgreSQL setup **
database_1  | postgresql 18:58:05.62 INFO  ==> Validating settings in POSTGRESQL_* env vars..
database_1  | postgresql 18:58:05.62 ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
database_1  | postgresql 18:58:05.63 ERROR ==> The POSTGRESQL_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
<container stops>
```
**Describe the results you expected:**

I expected the container to boot and replicate as it has in the past.

**Additional information you deem important (e.g. issue happens only occasionally):**

I've discovered that it will work if you add the `ALLOW_EMPTY_PASSWORD=yes` - which is not included or mentioned as necessary for replication in the documentation. And using this will always warn you that it shouldn't be used in a production environment (I would like this to be a production environment).

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 16
  Running: 14
  Paused: 0
  Stopped: 2
 Images: 30
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-72-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: lbnext20
 ID: 5TCI:JBNJ:YRHD:RU7N:47OF:WPJH:NTBD:CDUQ:TZCI:FRDA:MGZD:C7YX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://wwwproxy.sandia.gov:80/
 HTTPS Proxy: http://wwwproxy.sandia.gov:80/
 No Proxy: sandia.gov,.sandia.gov
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I am working on an Ubuntu 18.04 machine. My old setup, on Ubuntu 16.04, did not have this bug (and it is working from the same tag, though maybe it hasn't refreshed in awhile).

From inside the container:
echo $BITNAMI_IMAGE_VERSION
11.6.0-debian-9-r42

**Comment by miguelaeh** [comment]
Hi @ewalkup ,
The `ALLOW_EMPTY_PASSWORD=yes` allows you to connect to the database without using a password, that is why it is not recommended for production environments.
To create a `docker-compose.yaml` using passwords and replication you can follow the instructions on the `README.md`. You can find a docker-compose example [here](https://github.com/bitnami/bitnami-docker-postgresql#step-2-create-the-replication-slave) that uses replication and configures the passwords.

**Comment by ewalkup** [comment]
@miguelaeh I understand that, and I followed that example when creating my environment. The point of this issue is that example _does not work as is_. 

The replica _will _not__ start without either `ALLOW_EMPTY_PASSWORD=yes` or `POSTGRESQL_PASSWORD` (the example has neither). See logs in original post.

**Comment by miguelaeh** [comment]
Hi @ewalkup ,
That is the expected behaviour if you don't provide the password you need to provide the `ALLOW_EMPTY_PASSWORD` to allow the container to start without the password. 
By default, if you don't provide the `ALLOW_EMPTY_PASSWORD` nor the `POSTRGRESQL_PASSWORD` it will fail and show the error you got.

Regarding that `docker-compose.yml`, you are right it is wrong, the volumes are declared in a bad way. We will change it in the `README.md` in the mean time, the following is the correct `docker-compose.yml`:
```
version: '2'

services:
  postgresql-master:
    image: 'bitnami/postgresql:11-debian-9'
    ports:
      - '5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
  postgresql-slave:
    image: 'bitnami/postgresql:11-debian-9'
    ports:
      - '5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - 'postgresql_slave_data:/bitnami/postgresql'

volumes:
  postgresql_master_data:

  postgresql_slave_data:
```
