### ISSUE TITLE
Not all slave entries are available

### ISSUE THREAD

**Issue by nemozar** [bitnami/bitnami-docker-postgresql#194]
Settings 1 master and 2 slaves with sync commit.

```
select application_name as server, state,
      sync_priority as priority, sync_state
      from pg_stat_replication;
```

return than 1'st sync_state sync and second potential.

```
$master = new PDO('pgsql:host=postgresql.master;dbname=my_database', 'postgres', 'my_password');
$slave1 = new PDO('pgsql:host=postgresql.slave1;dbname=my_database', 'postgres', 'my_password');

for ($i=0 ; $i < 1000; $i++) {
    $last_id = $master->query("insert into public.newtable (data) values ('".uniqid()."') returning id;")->fetch()['id'];
    $selectSlave1  = $slave1->query('select * from public.newtable where id='.$last_id);
    if ($selectSlave1->fetch()) {
        $return['slave1']++;
    }
```

After insert master server request slave1 and find inserted row. From 1000 insret row in master at slave succesfull get 995-1000 (random count).

docker-compose:
```
version: '2'
#postgresmasterslave
services:
  postgresql.master:
    image: 'bitnami/postgresql:12'
    container_name: postgresql.master
    ports:
      - 5435:5432
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
      - /private/var/www/docker/docker-stack/postgres_master_slave/conf.d:/bitnami/postgresql/conf/conf.d
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=2
      #- POSTGRESQL_CLUSTER_APP_NAME=master
    networks:
      - docker
  postgresql.slave1:
    image: 'bitnami/postgresql:12'
    container_name: postgresql.slave1
    ports:
      - 5436:5432
    depends_on:
      - postgresql.master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql.master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_CLUSTER_APP_NAME=slave1
    networks:
      - docker
  postgresql.slave2:
    image: 'bitnami/postgresql:12'
    container_name: postgresql.slave2
    ports:
      - 5437:5432
    depends_on:
      - postgresql.master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql.master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_CLUSTER_APP_NAME=slave2
    networks:
      - docker
volumes:
  postgresql_master_data:
    driver: local
networks:
  docker:
    external:
      name: docker
```

/bitnami/postgresql/conf/conf.d/master.conf: **synchronous_standby_names='slave1,slave2'**

![image](https://user-images.githubusercontent.com/4721820/74111067-b4e65300-4ba2-11ea-9872-ec45f6d57343.png)
