### ISSUE TITLE
Support docker secrets

### ISSUE THREAD

**Issue by nollymar** [bitnami/bitnami-docker-postgresql#195]
**Description**

It would be great to set sensitive information like db passwords using docker secrets instead of environment variables

**Comment by andresbono** [comment]
Thanks for suggesting it! It seems like an interesting feature to support. We are going to evaluate it and we will get back to you. We will keep this issue open in the meantime.

**Comment by andresbono** [comment]
Hi @nollymar again, we will need to check the containers case by case but for PostgreSQL, you should be able to do something like this:

```
version: "3.6"

services:
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - 'POSTGRESQL_PASSWORD_FILE=/run/secrets/my_secret'
    secrets:
      - my_secret

secrets:
  my_secret:
    file: ./my_secret.txt
```

Let us know if this is what you are looking for!
