### ISSUE TITLE
Recommended way to back up a database?

### ISSUE THREAD

**Issue by dominikkrulak** [bitnami/bitnami-docker-postgresql#196]
There are several of blog posts and advices on how to back up PostgreSQL database. 
I've tried couple of them like

`docker exec postgres_container_name pg_dump -U username database_name > your_backup.sql`
or from [this tip](https://gist.github.com/gilyes/525cc0f471aafae18c3857c27519fc4b)
`docker exec -t -u username postgres_container_name pg_dumpall -c > your_backup.sql`

and yet I wasn't able to create a backup file.
Even with the `postgres` user.

Either 
`pg_dump: error: connection to database "c" failed: fe_sendauth: no password supplied`
or
`user username not found in passwd file`

I also tried
```
volumes:
      - type: bind
        source: ./.pgpass
        target: /bitnami/postgresql/conf/.pgpass
        read_only: true
environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${PGDB_PGDB_PASSWORD}
      - POSTGRESQL_PASSWORD_FILE=/bitnami/postgresql/conf/.pgpass
```
and in _Dokerfile_
```
ADD .pgpass /bitnami/postgresql/conf/
RUN chmod 0600 /bitnami/postgresql/conf/.pgpass
```
_.pgpass_ file
`host:port:dbname:user`

_docker-compose.yml_ file
```
  # ...
  pgdb:
    image: debian10/postgresql:12.2.0
    container_name: pgdb
    ports:
      - "5432"
    volumes:
      - type: bind
        source: ./src/postgresql/conf/postgresql.conf
        target: /bitnami/postgresql/conf/postgresql.conf
        read_only: true
      - type: bind
        source: ./src/postgresql/conf/.pgpass
        target: /bitnami/postgresql/conf/.pgpass
        read_only: true
      - type: volume
        source: pgdb-test
        target: /bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${PGDB_PGDB_PASSWORD}
      - POSTGRESQL_PASSWORD_FILE=/bitnami/postgresql/conf/.pgpass
      #- POSTGRESQL_USERNAME=${PGDB_USER}
      #- POSTGRESQL_PASSWORD=${PGDB_PASSWORD}
      #- POSTGRESQL_DATABASE=${PGDB_DB}
    restart: always
```
**`BITNAMI_IMAGE_VERSION="12.2.0-debian-10-r5"`**

**Comment by rafariossaa** [comment]
Hi @dominikkrulak ,
  Could you share the docker compose file you are using ?

**Comment by rafariossaa** [comment]
Hi, @dominikkrulak 
  First, a couple of details, the environment var to set the posgresql admin user password is ` POSTGRESQL_PASSWORD`, and `POSTGRESQL_PASSWORD_FILE` should point to a file have the user password. You can use one or other to set the admin password, but not both.
  To make a backup, I used the following compose:

```
version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:11'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=qwerty
volumes:
  postgresql_data:
    driver: local
```
and then
   `docker exec -e PGPASSWORD=qwerty  bitnami-docker-postgresql_postgresql_1  pg_dump -U postgres postgres > dump_test`

Note that `bitnami-docker-postgresql_postgresql_1` is the name of the running container.
