### ISSUE TITLE
Unable to use custom postgresql.conf

### ISSUE THREAD

**Issue by manami520** [bitnami/bitnami-docker-postgresql#205]
**Description**
I'd like to customize postgres.conf and followed the steps written in the readme.
but after restart container, postgres.conf of host was overwritten to default conf file.
Log says 'postgresql.conf file not detected.', but postgresql.conf exists in mounted directory and after restarted conf file in host was over written.
I have no idea to deal with.
Could you please give some advice?
**Log**
```
postgresql 00:33:28.43
postgresql 00:33:28.43 Welcome to the Bitnami postgresql container
postgresql 00:33:28.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 00:33:28.43 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 00:33:28.44 Send us your feedback at containers@bitnami.com
postgresql 00:33:28.44
postgresql 00:33:28.44 DEBUG ==> Configuring libnss_wrapper...
postgresql 00:33:28.45 INFO  ==> ** Starting PostgreSQL setup **
postgresql 00:33:28.49 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 00:33:28.49 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
postgresql 00:33:28.50 INFO  ==> Loading custom pre-init scripts...
postgresql 00:33:28.50 INFO  ==> Initializing PostgreSQL database...
postgresql 00:33:28.50 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql 00:33:28.51 DEBUG ==> Ensuring expected directories/files exist...
postgresql 00:33:28.51 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 00:33:28.52 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 00:33:28.52 INFO  ==> Generating local authentication configuration
postgresql 00:33:28.53 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 00:33:28.53 INFO  ==> Configuring replication parameters
postgresql 00:33:28.55 INFO  ==> Configuring fsync
postgresql 00:33:28.55 INFO  ==> Loading custom scripts...
postgresql 00:33:28.56 INFO  ==> Enabling remote connections
postgresql 00:33:28.56 INFO  ==> Stopping PostgreSQL...
postgresql 00:33:28.57 INFO  ==> ** PostgreSQL setup finished! **

postgresql 00:33:28.61 INFO  ==> ** Starting PostgreSQL **
```
**file ownership**
```
drwxrwxr-x 2 1001 1001  4096 Jan  8 01:34 conf.d
-rw-r--r-- 1 1001 1001   213 Mar 27 09:33 pg_hba.conf
-rw-r--r-- 1 1001 root   23723 Mar 27 09:33 postgresql.conf
```
**docker-compose.yml**
```
~~
 postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - '/home/sv-waza/work/docker/discourse/postgresql_data/conf:/opt/bitnami/postgresql/conf'
~~
```

**Comment by Mauraza** [comment]
Hi @manami520,

The problem is the volume of the docker-compose, 
Have yo to be `/path/to/postgresql-persistence/conf/:/bitnami/postgresql/conf/` not '/opt/bitnami/postgresql/conf'

```
 postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - '/home/sv-waza/work/docker/discourse/postgresql_data/conf:/bitnami/postgresql/conf'
```
