### ISSUE TITLE
Could not setup postgresql database with jfrog artifactory

### ISSUE THREAD

**Issue by othomann** [bitnami/bitnami-docker-postgresql#212]
Hi,
I have issues to setup a postgresql database using your chart on a kubernetes cluster.

This is the log I am getting:
```
postgresql 01:27:55.06
postgresql 01:27:55.06 Welcome to the Bitnami postgresql container
postgresql 01:27:55.06 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 01:27:55.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 01:27:55.07 Send us your feedback at containers@bitnami.com
postgresql 01:27:55.07
postgresql 01:27:55.09 INFO  ==> ** Starting PostgreSQL setup **
postgresql 01:27:55.17 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 01:27:55.17 INFO  ==> Loading custom pre-init scripts...
postgresql 01:27:55.18 INFO  ==> Initializing PostgreSQL database...
postgresql 01:27:55.21 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 01:27:55.23 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 01:27:55.23 INFO  ==> Generating local authentication configuration
postgresql 01:27:55.24 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 01:27:55.25 INFO  ==> Configuring replication parameters
postgresql 01:27:55.28 INFO  ==> Configuring fsync
postgresql 01:27:55.29 INFO  ==> Loading custom scripts...
postgresql 01:27:55.30 INFO  ==> Enabling remote connections
postgresql 01:27:55.31 INFO  ==> Stopping PostgreSQL...
postgresql 01:27:55.32 INFO  ==> ** PostgreSQL setup finished! **

postgresql 01:27:55.39 INFO  ==> ** Starting PostgreSQL **
LOG:  database system was shut down at 2020-05-01 01:27:37 GMT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```
But when the artifactory pod is starting, the wait-for-db init container never returns. It does this:
```yaml
      - command:
        - sh
        - -c
        - |
          until nc -z -w 2 artifactory-postgresql 5432 && echo database ok; do
            sleep 2;
          done;
        image: alpine:3.10
        imagePullPolicy: IfNotPresent
        name: wait-for-db
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```
I am not sure what is not working with the database pod. In the values.yaml, this is the setting for the database:
```yaml
postgresql:
  enabled: false
  volumePermissions:
    enabled: true
  image:
    registry: docker.bintray.io
    repository: bitnami/postgresql
    tag: 9.6.17-debian-10-r21
  postgresqlUsername: artifactory
  postgresqlPassword: <my password>
  postgresqlDatabase: artifactory
  postgresqlExtendedConf:
    listenAddresses: "'*'"
    maxConnections: "1500"
  persistence:
    enabled: true
    size: 50Gi
  service:
    port: 5432
  resources: {}
  nodeSelector: {}
```
Any idea what could be wrong? I also tried a sonarqube deployment and I have similar issues with the postgresql database pod.

Thank you.

**Comment by carrodher** [comment]
Hi, what chart are you using? Apart from the above code blocks, do you implement other changes or customization?

I would like to reproduce the issue by using the same environment.

**Comment by othomann** [comment]
The dependency I have is:
dependencies:
  - name: postgresql
    version: 8.7.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

**Comment by carrodher** [comment]
I tried to install the postgresql chart but using your parameters:
```yaml
volumePermissions:
  enabled: true
image:
  registry: docker.bintray.io
  repository: bitnami/postgresql
  tag: 9.6.17-debian-10-r21
postgresqlUsername: artifactory
postgresqlPassword: SOME_PASSWORD
postgresqlDatabase: artifactory
postgresqlExtendedConf:
  listenAddresses: "'*'"
  maxConnections: "1500"
persistence:
  enabled: true
  size: 50Gi
service:
  port: 5432
resources: {}
nodeSelector: {}
```
Please, note that I removed the `postgresql.enabled=false`.

Then I deployed the postgresql chart using those options by running
```console
$ helm install --generate-name bitnami/postgresql -f values2.yaml
```
Everything seems to work as expected:
```
kubectl logs -f postgresql-1588574861-postgresql-0
postgresql 06:48:25.44
postgresql 06:48:25.49 Welcome to the Bitnami postgresql container
postgresql 06:48:25.49 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 06:48:25.49 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 06:48:25.50 Send us your feedback at containers@bitnami.com
postgresql 06:48:25.50
postgresql 06:48:25.55 INFO  ==> ** Starting PostgreSQL setup **
postgresql 06:48:25.64 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 06:48:25.65 INFO  ==> Loading custom pre-init scripts...
postgresql 06:48:25.71 INFO  ==> Initializing PostgreSQL database...
postgresql 06:48:25.79 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 06:48:25.81 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 06:48:25.82 INFO  ==> Generating local authentication configuration
postgresql 06:48:28.49 INFO  ==> Starting PostgreSQL in background...
postgresql 06:48:29.81 INFO  ==> Creating user artifactory
postgresql 06:48:29.83 INFO  ==> Grating access to "artifactory" to the database "artifactory"
postgresql 06:48:29.86 INFO  ==> Configuring replication parameters
postgresql 06:48:29.89 INFO  ==> Configuring fsync
postgresql 06:48:29.91 INFO  ==> Loading custom scripts...
postgresql 06:48:29.91 INFO  ==> Enabling remote connections
postgresql 06:48:29.93 INFO  ==> Stopping PostgreSQL...
postgresql 06:48:30.95 INFO  ==> ** PostgreSQL setup finished! **

postgresql 06:48:31.01 INFO  ==> ** Starting PostgreSQL **
LOG:  database system was shut down at 2020-05-04 06:48:29 GMT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```

With the following commands I was able to connect to the postgresql pod and perform some actions:
```console
$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-1588574861 -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ kubectl run postgresql-1588574861-client --rm --tty -i --restart='Never' --namespace default --image docker.bintray.io/bitnami/postgresql:9.6.17-debian-10-r21 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host postgresql-1588574861 -U artifactory -d artifactory -p 5432

artifactory=> \l
                                    List of databases
    Name     |  Owner   | Encoding |   Collate   |    Ctype    |    Access privileges
-------------+----------+----------+-------------+-------------+--------------------------
 artifactory | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres            +
             |          |          |             |             | postgres=CTc/postgres   +
             |          |          |             |             | artifactory=CTc/postgres
 postgres    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres             +
             |          |          |             |             | postgres=CTc/postgres
 template1   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres             +
             |          |          |             |             | postgres=CTc/postgres
(4 rows)

artifactory=>
```

According to that, the postgresql subchart seems to be working as expected (not sure if you can do the same checks on your side).
