### ISSUE TITLE
How to create a replication master-master

### ISSUE THREAD

**Issue by Ignis-Divine** [bitnami/bitnami-docker-postgresql#219]
How to create a replication master-master?

Thanks!

**Comment by dani8art** [comment]
Hi @Ignis-Divine , could you give us a bit more info? 

- Are you using a docker/docker-compose environment or Kubernetes environment?

**Comment by Ignis-Divine** [comment]
Docker only

**Comment by dani8art** [comment]
Did you try this?

```yaml
version: "2"

services:
  postgresql-master-0:
    image: "docker.io/bitnami/postgresql:11-debian-10"
    ports:
      - "5432"
    volumes:
      - "postgresql_master_0_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-master-1:
    image: "docker.io/bitnami/postgresql:11-debian-10"
    ports:
      - "5432"
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "postgresql_master_1_data:/bitnami/postgresql"
volumes:
  postgresql_master_0_data:
    driver: local
  postgresql_master_1_data:
    driver: local
```
