### ISSUE TITLE
support alpine based postgres images

### ISSUE THREAD

**Issue by chukka** [bitnami/bitnami-docker-postgresql#221]
**Description**
Hi Team,

[We](https://github.com/jfrog/charts/blob/master/stable/artifactory/requirements.yaml) use bitnami helm charts for postgresql, mongodb and rabbitmq. These charts use debain based docker images which are quite large and prone to security vulnerabilities 

For example :

```
postgresql:
  enabled: true
  image:
    registry: docker.bintray.io
    repository: bitnami/postgresql
    tag: 9.6.17-debian-10-r72

```
Is there any plan to support alpine based images ? If yes, any ETA ?

Also, we tried to override docker image with alpine images in bitnami charts  and seems like they are not compatible ? Any workaround please ? 

```
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: 9.6.18-alpine
```

Thanks
Ram
