### ISSUE TITLE
Docker for Windows (latest) Permission denied mkdir (when persistence enabled)

### ISSUE THREAD

**Issue by samuk190** [bitnami/bitnami-docker-postgresql#237]
**Description**

  postgresql:
    container_name: postgresql
    image: 'bitnami/postgresql:latest'
    networks:
      - "app-network"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ravigilancia
    volumes:
      - /docker/postgresqldata/conf/:/bitnami/postgresql/conf/
      - /docker/postgresql-persistence:/bitnami/postgresql

**Steps to reproduce the issue:**

1. docker-compose build
2. docker-compose up

**Describe the results you received:**
postgresql    | mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
postgresql    | postgresql 07:37:35.78 INFO  ==> Stopping PostgreSQL...        
postgresql exited with code 1

**Describe the results you expected:**

 start sucessfully.

I don't have an idea why that happens, I did fileshare correctly in my docker settings, its mounted on C:

**Comment by marcosbc** [comment]
Hi @samuk190, I'm unfamiliar with the Docker on Windows filesystem permissions when mounting onto containers, but you may be able to solve this with an init container for fixing permissions:

```diff
 version: '2'

 services:
+  fixPermissions:
+    image: 'docker.io/bitnami/postgresql:11-debian-10'
+    user: root
+    command: chown -R 1001:1001 /bitnami/postgresql
+    volumes:
+      - 'postgresql_data:/bitnami/postgresql'
   postgresql:
+    depends_on:
+      - fixPermissions
     image: 'docker.io/bitnami/postgresql:11-debian-10'
     ports:
       - '5432:5432'
```

Hope it works!

**Comment by samuk190** [comment]
> Hi @samuk190, I'm unfamiliar with the Docker on Windows filesystem permissions when mounting onto containers, but you may be able to solve this with an init container for fixing permissions:
> 
> ```diff
>  version: '2'
> 
>  services:
> +  fixPermissions:
> +    image: 'docker.io/bitnami/postgresql:11-debian-10'
> +    user: root
> +    command: chown -R 1001:1001 /bitnami/postgresql
> +    volumes:
> +      - 'postgresql_data:/bitnami/postgresql'
>    postgresql:
> +    depends_on:
> +      - fixPermissions
>      image: 'docker.io/bitnami/postgresql:11-debian-10'
>      ports:
>        - '5432:5432'
> ```
> 
> Hope it works!

Hi, it doesnt work 
postgresql        | postgresql 14:00:15.24 INFO  ==> Loading custom pre-init scripts...
postgresql        | postgresql 14:00:15.25 INFO  ==> Initializing PostgreSQL database...
postgresql        | postgresql 14:00:15.31 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql        | postgresql 14:00:15.32 INFO  ==> Generating local authentication configuration

homewever it does create folders, but it doesnt write data.

Strange because bitnami/nginx works fine, why bitnami postgresql doesnt have the same behaviour? 

I also tried: RUN chown -R 1001:1001 /usr/app
on my dockerfile build

**Comment by samuk190** [comment]
```
version: "3.1"
services:
  fixPermissions:
   image: 'docker.io/bitnami/postgresql:11-debian-10'
   user: root
   command: chown -R 1001:1001 /bitnami/postgresql
   volumes:
      - './docker/postgresql-persistence:/bitnami/postgresql'
  nginx:
    image: bitnami/nginx:latest
    networks:
      - "app-network"
    container_name: nginx
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./docker/nginx/my_server_block.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
      # - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      # - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
      # - ./docker/nginx-conf:/etc/nginx/conf.d
    env_file: ./.env.development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  postgresql:
    container_name: postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    image: 'bitnami/postgresql:latest'
    networks:
      - "app-network"
    ports:
      - "5432:5432"
    depends_on:
      - fixPermissions
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ravigilancia
    # volumes:
    #   - ./docker/postgresqldata/conf/:/bitnami/postgresql/conf/
    #   - ./docker/postgresql-persistence:/bitnami/postgresql

  mongodb:
     container_name: mongodb
     image: 'bitnami/mongodb:latest'
     environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_DATABASE=ravigilancia
     ports:
      - "27017:27017"
     networks:
      - "app-network"
     volumes:
      - mongodata:/bitnami/mongodb
     logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  app:
    build: .
    command: yarn dev
    command: bash -c "./wait-for-it.sh postgresql:5432 -t 0 -s && npx sequelize-cli db:migrate && yarn dev"
    ports:
      - "3333:3333"
    container_name: raserver
    working_dir: /usr/raserver
    volumes:
      - .:/usr/raserver
    env_file: ./.env.development
    environment:
      "NODE_ENV": "development"
    networks:
      - "app-network"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    volumes:
      - ./docker/redis-persistence:/bitnami/redis/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
networks:
  app-network:
    driver: bridge
volumes:
  mongodata:

```

docker compose
