### ISSUE TITLE
Container should not require writing as root group

### ISSUE THREAD

**Issue by jameswynn** [bitnami/bitnami-docker-postgresql#242]
**Description**

The container relies on membership in the root group for write access to /opt/bitnami. Many enterprise PSPs prohibit this access, so it is problematic. Why not make that directory structure also owned by the 1001 group?

**Steps to reproduce the issue:**

1. Deploy a PSP which places restrictions on the group
2. Deploy the container

**Describe the results you received:**

Container fails to start due to a "Permission Denied" error while copying to /opt/bitnami/postgresql/conf/postresql.conf

**Describe the results you expected:**

Container starts normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

Chart is stable/postgresql (deprecated, I know) via stable/airflow. Postgresql image is 11.7.0.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running in Rancher 2.4.3 with Kubernetes 1.17.5.

**Comment by andresbono** [comment]
Hi @jameswynn, we would like to test the scenario that you are describing so we can evaluate it. Which values are you using? Are you using `psp.create=true`? Are you modifying [bitnami/postgresql/templates/podsecuritypolicy.yaml](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/podsecuritypolicy.yaml)?

**Comment by jameswynn** [comment]
We are not using the embedded PSP. The PSP we are running under restricts the supplementalGroups like this excerpt:

```yaml
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1000
      max: 1001
```

We are using the default securityContext definition in the chart, but I have tried it with other values.

**Comment by andresbono** [comment]
Hi @jameswynn, thanks for the additional information. We were able to reproduce your issue with the stable/postgresql chart. We added the property `runAsGroup: 1001` to the security group of the container:

https://github.com/helm/charts/blob/a314ffbe98816970be9b692918d79b2be54ac794/stable/postgresql/templates/statefulset.yaml#L131-L132

```
...
postgresql 10:34:39.64 INFO  ==> ** Starting PostgreSQL setup **
postgresql 10:34:39.68 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 10:34:39.68 INFO  ==> Loading custom pre-init scripts...
postgresql 10:34:39.68 INFO  ==> Initializing PostgreSQL database...
postgresql 10:34:39.69 INFO  ==> postgresql.conf file not detected. Generating it...
cp: cannot create regular file '/opt/bitnami/postgresql/conf/postgresql.conf': Permission denied
postgresql 10:34:39.70 INFO  ==> Stopping PostgreSQL...
```

The reason behind the decision to set the group ownership to root is because some Kubernetes environments set a random UUID but a deterministic group, `root`. We rely on this fact in order to allow the container to write in those directories.

I'm not really sure how can this be improved, but please let us know any implementation suggestions that you may have and we can evaluate it.

Please also note that the stable/postgresql chart won't receive any new updates or fixes. In order for you to continue working, we can just suggest you to create some extra volumes so the configuration files can be created. Something like the following:

```
master:
  extraVolumeMounts:
    - name: writableconf
      mountPath: /opt/bitnami/postgresql/conf
    - name: writableconfd
      mountPath: /opt/bitnami/postgresql/conf/conf.d
    - name: writabletmp
      mountPath: /opt/bitnami/postgresql/tmp
  extraVolumes:
    - name: writableconf
      emptyDir: {}
    - name: writableconfd
      emptyDir: {}
    - name: writabletmp
      emptyDir: {}
```

The previous custom values.yaml worked for us to solve the issue.
