### ISSUE TITLE
pg_hba.conf handling inconsistent

### ISSUE THREAD

**Issue by JonEngle** [bitnami/bitnami-docker-postgresql#257]
**Description**

Using very basic postgresql config, **pg_hba.conf** will get created properly when no database exists.  However, if the container is restarted, **pg_hba.conf** is not the same.

At the same time, if **pg_hba.conf** is specified in the helm chart, the database won't be initialized.

**Steps to reproduce the issue:**

I'm using helm to drive this, but I don't think the issue is in the helm chart.

values.yaml driving this (redacted of course):

```yaml
postgresql:
  postgresqlUsername: "foo"
  postgresqlPassword: "bar"
  postgresqlDatabase: "foobar"
  postgresqlPostgresPassword: "barfoo"
  tls:
    enabled: true
    certificatesSecret: "the-postgresql-cert"
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    certCAFilename: "ca.crt" (add the desired CA as part of the secret)
```

**Describe the results you received:**

On first-time initialization, database foobar is created, along with user foo with pwd bar, and postgres has password barfoo.  **pg_hba.conf** is created with the hostssl entries, so cert auth can be used.

Kill the postgresql pod or helm uninstall it.  PVC still there (expected).  On second start, pg_hba.conf is recreated, but no hostssl entries.

**Describe the results you expected:**

**pg_hba.conf**, if generated, should be generated consistently on pod restart.

**Additional information you deem important (e.g. issue happens only occasionally):**

This looks wrong:
https://github.com/bitnami/bitnami-docker-postgresql/blame/master/12/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L640
It looks like it should be scope outside of the if/else block it's in.

**Version**

The other versions shouldn't really matter here (will provide if you insist).  The container version is `bitnami/postgresql:12-debian-10`
