### ISSUE TITLE
POSTGRESQL_POSTGRES_PASSWORD doesn't work

### ISSUE THREAD

**Issue by xcg-star** [bitnami/bitnami-docker-postgresql#262]
docker-compose.yml:
```
version: '2'

services:
  postgresql-master:
    image: 'docker.io/bitnami/postgresql:12-debian-10'
    container_name: postgresql-master
    ports:
      - 5432:5432
    volumes:
      - './pg-master/:/bitnami/postgresql/:rw'
      - './pg-master/:/opt/bitnami/postgresql/conf/:rw'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=tests
      - POSTGRESQL_REPLICATION_PASSWORD=test2020s
      - POSTGRESQL_USERNAME=testm
      - POSTGRESQL_PASSWORD=test2020m
      - POSTGRESQL_DATABASE=test_db
      - POSTGRESQL_POSTGRES_PASSWORD=pass2020
  postgresql-slave:
    image: 'docker.io/bitnami/postgresql:12-debian-10'
    container_name: postgresql-slave
    ports:
      - 5433:5432
    volumes:
      - './pg-slave/:/bitnami/postgresql/:rw'
      - './pg-slave/:/opt/bitnami/postgresql/conf/:rw'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=tests
      - POSTGRESQL_REPLICATION_PASSWORD=test2020s
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_USERNAME=testm
      - POSTGRESQL_PASSWORD=test2020m
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_POSTGRES_PASSWORD=pass2020
```

```
[root@TEST postgresql]# docker-compose restart
[root@TEST postgresql]# docker exec -it postgresql-master bash
I have no name!@b6cf0a059e2b:/$ psql -U postgres -d test_db
Password for user postgres:pass2020
psql: error: could not connect to server: FATAL:  password authentication failed for user "postgres"
```

**Comment by dani8art** [comment]
Hi @xcg-star thanks for reporting it, I was taking a look at the `docker-compose.yaml` and doing some testing, finally, I found the problem. It seems like this volume is conflicting with the initialization logic `'./pg-slave/:/opt/bitnami/postgresql/conf/:rw'` if you remove it the postgresql work fine. 

```
I have no name!@7ce8baa747eb:/$ PGPASSWORD=pass2020 psql -U postgres -d test_db
psql (12.5)
Type "help" for help.

test_db=#
```

why do you need to persist it?

**Comment by xcg-star** [comment]
@dani8art 
thanks for answering,
i tried to remove the volume and execute 
`docker-compose down` and `docker-compose up -d`,but it's no use.
should i execute `docker-compose stop` `docker-compose rm` or modify some file in path pg-master/ and pg-slave/ ?

**Comment by xcg-star** [comment]
i deleted data and restart, it works.
what's the reason?
is the password of user POSTGRES set to a random string when i didn't add POSTGRESQL_POSTGRES_PASSWORD？

**Comment by dani8art** [comment]
> what's the reason?

`./data` is used to determine whether the database and passwords were already created or not.

> is the password of user POSTGRES set to a random string when i didn't add POSTGRESQL_POSTGRES_PASSWORD？

No, if you don't set `POSTGRESQL_POSTGRES_PASSWORD`, it will have not password.

**Comment by Cililing** [comment]
Hi, I have a similar issue.
In my case I run docker compose via ansible-playbook:

```
- name: Run postgres docker image (primary)
  become: yes
  docker_container:
    name: postgres-primary
    image: bitnami/postgresql:12
    restart_policy: always
    state: started
    volumes:
      - "{{ postgres_root }}/persistence:/bitnami/postgresql"
    env:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_USERNAME: "{{ sql_user }}"
      POSTGRESQL_PASSWORD: "{{ sql_password }}"
      POSTGRESQL_DATABASE: "{{ sql_db }}"
      POSTGRESQL_REPLICATION_USER: "{{ sql_repl_user }}"
      POSTGRESQL_REPLICATION_PASSWORD: "{{ sql_repl_pass }}"
    ports:
      - "{{ postgres_bind_port }}:{{ _postgres_bind_port }}"
```

As I understand - with such a provision a `postgres` user should have `{{ sql_password }}` (let's say it's `abcd1234`), am I right? But, when I try to login into the database (enter docker container, then `psql -U postgres`) I get an error:

```
$ psql -U postgres
Password for user postgres: abcd1234
psql: error: FATAL:  password authentication failed for user "postgres"
```
