### ISSUE TITLE
Won't start anymore with a custom port 

### ISSUE THREAD

**Issue by CVois1** [bitnami/bitnami-docker-postgresql#268]
**Description**

The postgres 11 won't start anymore with a custom port 
**Steps to reproduce the issue:**

Set up a docker compose file like the following one i.e. a kong service with a PostgreSQL DB
```
  kong-db:
    image: bitnami/postgresql:11
    container_name: kong-db
    ports:
      - '5532:5532'
    volumes:
      - kong_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=xxx
      - POSTGRESQL_PASSWORD=yyy
      - POSTGRESQL_DATABASE=zzz
      - POSTGRESQL_PORT_NUMBER=5532
```

**Describe the results you expected:**
We expect a zzz DB up and running but the DB hang and will never start ...

If we set an older version, i.e. Nov 6th, the DB will start again !
```
  kong-db:
    image: bitnami/postgresql:11.9.0-debian-10-r75
    container_name: kong-db
    ports:
      - '5532:5532'
    volumes:
      - kong_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=xxx
      - POSTGRESQL_PASSWORD=yyy
      - POSTGRESQL_DATABASE=zzz
      - POSTGRESQL_PORT_NUMBER=5532
```
