### ISSUE TITLE
Small k8s deployment attempt - need clarification on init script

### ISSUE THREAD

**Issue by pranasblk** [bitnami/bitnami-docker-postgresql#270]
**Description**

Created minimalistic ks manifest, but getting authentication errors in container's run-time.
**Steps to reproduce the issue:**

Environment
```
apiVersion: v1
kind: Service

metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
    - name: tcp-postgresql
      port: 5432
  selector:
    name: postgresql
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql

spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRESQL_POSTGRES_PASSWORD
              value: password
            - name: POSTGRESQL_USERNAME
              value: quickfix
            - name: POSTGRESQL_PASSWORD
              value: password
            - name: POSTGRESQL_DATABASE
              value: quickfix
            - name: POSTGRESQL_VOLUME_DIR
              value: /bitnami/postgresql
            - name: PGDATA
              value: /bitnami/postgresql/data
          name: postgresql
          image: docker.io/bitnami/postgresql:11.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: tcp-postgresql
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /bitnami/postgresql
              name: data
      securityContext:
        fsGroup: 1001
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: dshm
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 8Gi```

1. [First Step]
apply manifest above.

2. [Second Step]
Check logs of pod.

```
/usr/local/bin/kubectl logs -f pods/postgresql-0 --namespace default
[38;5;6mpostgresql [38;5;5m03:04:14.92 [0m
[38;5;6mpostgresql [38;5;5m03:04:14.92 [0m[1mWelcome to the Bitnami postgresql container[0m
[38;5;6mpostgresql [38;5;5m03:04:14.92 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-postgresql[0m
[38;5;6mpostgresql [38;5;5m03:04:14.92 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-postgresql/issues[0m
[38;5;6mpostgresql [38;5;5m03:04:14.93 [0m
[38;5;6mpostgresql [38;5;5m03:04:14.94 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL setup **
[38;5;6mpostgresql [38;5;5m03:04:14.98 [0m[38;5;2mINFO [0m ==> Validating settings in POSTGRESQL_* env vars..
[38;5;6mpostgresql [38;5;5m03:04:14.98 [0m[38;5;2mINFO [0m ==> Loading custom pre-init scripts...
[38;5;6mpostgresql [38;5;5m03:04:14.99 [0m[38;5;2mINFO [0m ==> Initializing PostgreSQL database...
[38;5;6mpostgresql [38;5;5m03:04:15.00 [0m[38;5;2mINFO [0m ==> postgresql.conf file not detected. Generating it...
[38;5;6mpostgresql [38;5;5m03:04:15.01 [0m[38;5;2mINFO [0m ==> pg_hba.conf file not detected. Generating it...
[38;5;6mpostgresql [38;5;5m03:04:15.01 [0m[38;5;2mINFO [0m ==> Generating local authentication configuration
[38;5;6mpostgresql [38;5;5m03:04:15.02 [0m[38;5;2mINFO [0m ==> Deploying PostgreSQL with persisted data...
[38;5;6mpostgresql [38;5;5m03:04:15.02 [0m[38;5;2mINFO [0m ==> Configuring replication parameters
[38;5;6mpostgresql [38;5;5m03:04:15.04 [0m[38;5;2mINFO [0m ==> Configuring fsync
[38;5;6mpostgresql [38;5;5m03:04:15.04 [0m[38;5;2mINFO [0m ==> Loading custom scripts...
[38;5;6mpostgresql [38;5;5m03:04:15.04 [0m[38;5;2mINFO [0m ==> Enabling remote connections
[38;5;6mpostgresql [38;5;5m03:04:15.05 [0m[38;5;2mINFO [0m ==> Stopping PostgreSQL...

[38;5;6mpostgresql [38;5;5m03:04:15.05 [0m[38;5;2mINFO [0m ==> ** PostgreSQL setup finished! **
[38;5;6mpostgresql [38;5;5m03:04:15.09 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL **
2021-01-22 03:04:15.108 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-01-22 03:04:15.108 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-01-22 03:04:15.110 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-01-22 03:04:15.116 GMT [166] LOG:  database system was shut down at 2021-01-22 03:04:04 GMT
2021-01-22 03:04:15.120 GMT [1] LOG:  database system is ready to accept connections
```

3. Connect to pod and try to login:
```
✗ /usr/local/bin/kubectl exec -it pods/postgresql-0 --namespace default -- sh
$ ksql -U quickfix
sh: 1: ksql: not found
$ psql -U quickfix
Password for user quickfix: 
psql: FATAL:  password authentication failed for user "quickfix"
$ psql -U postgres
Password for user postgres: 
psql: FATAL:  password authentication failed for user "postgres"
```

**Describe the results you received:**

Getting FATAL errors regarding password setting
```
2021-01-22 03:05:04.504 GMT [187] FATAL:  password authentication failed for user "quickfix"
2021-01-22 03:05:04.504 GMT [187] DETAIL:  Role "quickfix" does not exist.
	Connection matched pg_hba.conf line 3: "local    all             all                                     md5"
2021-01-22 03:05:04.504 GMT [187] LOG:  could not send data to client: Broken pipe
2021-01-22 03:05:08.449 GMT [188] FATAL:  password authentication failed for user "quickfix"
2021-01-22 03:05:08.449 GMT [188] DETAIL:  Role "quickfix" does not exist.
	Connection matched pg_hba.conf line 3: "local    all             all                                     md5"
2021-01-22 03:05:24.806 GMT [191] FATAL:  password authentication failed for user "postgres"
2021-01-22 03:05:24.806 GMT [191] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 3: "local    all             all                                     md5"
2021-01-22 03:05:24.806 GMT [191] LOG:  could not send data to client: Broken pipe
2021-01-22 03:05:28.512 GMT [192] FATAL:  password authentication failed for user "postgres"
2021-01-22 03:05:28.512 GMT [192] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 3: "local    all             all                                     md5"

```
**Describe the results you expected:**

able to use posgres/password and quickfix/password without issues.
but got authentication errors.

**Additional information you deem important (e.g. issue happens only occasionally):**
Running on minikube with minikube proxy and expect local host to be functional:
```
service/postgresql   LoadBalancer   10.110.255.135   127.0.0.1     5432:32767/TCP   6m16s
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 17
  Running: 1
  Paused: 0
  Stopped: 16
 Images: 16
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: 4MJ3:VEFP:FMBM:J2AG:MEXZ:WS2U:HWET:3547:LS7J:KS6L:IYWC:R7TX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false```


**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Just regular new mac 

```
minikube version
minikube version: v1.16.0
``` where minikube is using docker for run-time.
