### ISSUE TITLE
Slave cannot connect to master

### ISSUE THREAD

**Issue by vhico07** [bitnami/bitnami-docker-postgresql#277]
Hi, i'm having trouble with connection slave to master, i got an errored like this
postgresql-master:5434 - no response
postgresql-master:5434 - no response
postgresql-master:5434 - no response
postgresql-master:5434 - no response
postgresql-master:5434 - no response
postgresql-master:5434 - no response
postgresql-master:5434 - no response
postgresql-master:5434 - no response

```
version: '2'

services:
  postgresql-master:
    image: 'docker.io/bitnami/postgresql:12-debian-10'
    container_name: postgresql-master
    ports:
      - '5434:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
      - './postgresql.conf:/opt/bitnami/postgresql/conf/postgresql.conf'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=password
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=postgres
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PGAUDIT_LOG=all, -mis
      - POSTGRESQL_PGAUDIT_LOG_CATALOG=off
  postgresql-slave:
    image: 'docker.io/bitnami/postgresql:12-debian-10'
    container_name: postgresql-slave
    ports:
      - '5434'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=password
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_PORT_NUMBER=5434
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  postgresql_master_data:
    driver: local`
```
    
Anyone have same problem?
