### ISSUE TITLE
Persisting config data - User 'postgres' has no password assigned

### ISSUE THREAD

**Issue by inzanez** [bitnami/bitnami-docker-postgresql#284]
Hi

I'm seeing some difficulties with persisting config data in `/opt/bitnami/postgresql/conf`. Everything works fine, but as soon as I mount a volume as follows:

```
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgres-data
            - mountPath: /opt/bitnami/postgresql/conf
              name: postgres-config-data
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: postgres-config-data
          persistentVolumeClaim:
            claimName: postgres-config-data
```

I cannot login with the user `postgres` anymore.

The env-variables used to init the `postgres` user is:
`POSTGRESQL_POSTGRES_PASSWORD: SomePassword`
