### ISSUE TITLE
Operation not permitted: changing permissions of data dir

### ISSUE THREAD

**Issue by thejasn** [bitnami/bitnami-docker-postgresql#285]
**Description**
Facing permission problems when installing postgres for "superset". As per my understanding the initContainer is responsible for chaning data dir ownership and thereby has the `securityContext: 0` (as default), this worked without issues. But the main container crashes due to the following error,
```
postgresql 16:31:16.05 
postgresql 16:31:16.07 Welcome to the Bitnami postgresql container
postgresql 16:31:16.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 16:31:16.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 16:31:16.07 
postgresql 16:31:16.09 INFO  ==> ** Starting PostgreSQL setup **
postgresql 16:31:16.12 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 16:31:16.13 INFO  ==> Loading custom pre-init scripts...
postgresql 16:31:16.14 INFO  ==> Initializing PostgreSQL database...
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 16:31:16.15 WARN  ==> Lack of permissions on data directory!
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 16:31:16.16 WARN  ==> Lack of permissions on data directory!
postgresql 16:31:16.16 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 16:31:16.16 INFO  ==> Generating local authentication configuration
```
This is my statefulset.yaml, 
```
---
# Source: superset/charts/postgresql/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: superset-postgresql
  namespace: "superset"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.2.0
    app.kubernetes.io/instance: superset
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  serviceName: superset-postgresql-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: superset
      role: primary
  template:
    metadata:
      name: superset-postgresql
      labels:
        app.kubernetes.io/name: postgresql
        helm.sh/chart: postgresql-10.2.0
        app.kubernetes.io/instance: superset
        app.kubernetes.io/managed-by: Helm
        role: primary
        app.kubernetes.io/component: primary
    spec:      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: postgresql
                    app.kubernetes.io/instance: superset
                    app.kubernetes.io/component: primary
                namespaces:
                  - superset
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: init-chmod-data
          image: docker.io/bitnami/minideb:buster
          imagePullPolicy: "Always"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          command:
            - /bin/sh
            - -cx
            - |
              chown 1001:1001 /bitnami/postgresql
              mkdir -p /bitnami/postgresql/data
              chmod 700 /bitnami/postgresql/data
              find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name "conf" -not -name ".snapshot" -not -name "lost+found" | \
                xargs chown -R 1001:1001
              chmod -R 777 /dev/shm
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
              subPath: 
            - name: dshm
              mountPath: /dev/shm
      containers:
        - name: superset-postgresql
          image: docker.io/bitnami/postgresql:11.10.0-debian-10-r24
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_VOLUME_DIR
              value: "/bitnami/postgresql"
            - name: PGDATA
              value: "/bitnami/postgresql/data"
            - name: POSTGRES_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: superset-postgresql
                  key: postgresql-postgres-password
            - name: POSTGRES_USER
              value: "superset"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: superset-postgresql
                  key: postgresql-password
            - name: POSTGRES_DB
              value: "superset"
            - name: POSTGRESQL_ENABLE_LDAP
              value: "no"
            - name: POSTGRESQL_ENABLE_TLS
              value: "no"
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "false"
            - name: POSTGRESQL_LOG_CONNECTIONS
              value: "false"
            - name: POSTGRESQL_LOG_DISCONNECTIONS
              value: "false"
            - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
              value: "off"
            - name: POSTGRESQL_CLIENT_MIN_MESSAGES
              value: "error"
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit"
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "superset" -d "dbname=superset" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "superset" -d "dbname=superset" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /bitnami/postgresql
              subPath: 
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "2Gi"
        storageClassName: azurefile-wait-for-consumer
```

**Steps to reproduce the issue:**

1. It's upon startup, so applying the above statefulset should result in the error as mentioned.

**Describe the results you received:**
```
postgresql 16:31:16.05 
postgresql 16:31:16.07 Welcome to the Bitnami postgresql container
postgresql 16:31:16.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 16:31:16.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 16:31:16.07 
postgresql 16:31:16.09 INFO  ==> ** Starting PostgreSQL setup **
postgresql 16:31:16.12 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 16:31:16.13 INFO  ==> Loading custom pre-init scripts...
postgresql 16:31:16.14 INFO  ==> Initializing PostgreSQL database...
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 16:31:16.15 WARN  ==> Lack of permissions on data directory!
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
postgresql 16:31:16.16 WARN  ==> Lack of permissions on data directory!
postgresql 16:31:16.16 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 16:31:16.16 INFO  ==> Generating local authentication configuration

```

**Describe the results you expected:**

Successful running postgres pod

**Additional information you deem important (e.g. issue happens only occasionally):**

Cloud Provider: Azure
Kubernetes Version: v1.18.10
Superset: Master  branch ([commit](https://github.com/apache/superset/tree/e06290663a23740e9cd3f50f2913b016bd7f205f))
