### ISSUE TITLE
/docker-entrypoint-initdb.d works only for the default database

### ISSUE THREAD

**Issue by MatteoInfi** [bitnami/bitnami-docker-postgresql#291]
Not sure why but the `/docker-entrypoint-initdb.d/` is executed only in the default database.

```
CREATE DATABASE customDatabase;
CREATE EXTENSION IF NOT EXISTS "my-extension";
```

```
  postgres:
    image: docker.io/bitnami/postgresql:11
    ports:
      - 5432:5432
    volumes:
      - ./init-mydb.sql:/docker-entrypoint-initdb.d/init-mydb.sql
```

The script is executed, but the extension is only accessible in the `postgres` default database
