### ISSUE TITLE
Possible unexpected behavior due to `set -o errexit` and `... && return`

### ISSUE THREAD

**Issue by georglauterbach** [bitnami/bitnami-docker-postgresql#295]
**BUG REPORT INFORMATION**

Running PostgreSQL 13 in a K3s cluster. The container fails to start, exits with exit code 1. On a local setup, this is not the case. When starting manually, the second attempt succeeds. Nailed down the cause.

**Description**

Because `set -o errexit` is set in `setup.sh`, the init script may exit early unexpectedly and without an error message. When having a construct like

```sh
set -o errexit

function __do_something
{
  # return is __do_something_else returns true
  __do_something_else && return
  __maybe_something_else
}

function __do_something_else
{
  ...
  return false
}

function __maybe_something_else
{
  printf 'OH NO, THIS IS NEVER REACHED'
}
```

it will only work when `__do_something_else` return successfully. Otherwise, `set -o errexit` will exit the script early (with exit code 1) after `__do_something_else && return` returned a falsy value. `__maybe_something_else` is therefore never reached.

The same situation prevails in two scripts in this repository:

https://github.com/bitnami/bitnami-docker-postgresql/blob/master/13/debian-10/rootfs/opt/bitnami/scripts/postgresql/entrypoint.sh 

runs

https://github.com/bitnami/bitnami-docker-postgresql/blob/1ed797178a80d7e282062592996e158b9fe3d89a/13/debian-10/rootfs/opt/bitnami/scripts/postgresql/setup.sh#L7

where the function `postgresql_start_bg` from https://github.com/bitnami/bitnami-docker-postgresql/blob/master/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh is called:

https://github.com/bitnami/bitnami-docker-postgresql/blob/1ed797178a80d7e282062592996e158b9fe3d89a/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L736

an we have the situation from above. Because `is_postgresql_running` may return false, this line "fails" and the whole init procedure exists with 1.

**Steps to reproduce the issue:**

1. Have a K3s cluster
2. Use a similar deployments as below
3. Watch the pod restart endlessly

Deployment

```yaml
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: database

spec:
  replicas: 1
  selector:
    matchLabels:
      app: database

  template:
    metadata:
      labels:
        app: database

    spec:
      containers:
        - name: database
          image: docker.io/bitnami/postgresql:13.3.0
          imagePullPolicy: IfNotPresent

          args:
            - bash
          
          tty: true
          stdin: true

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 0
            runAsNonRoot: false
            privileged: false
            # capabilities:
              # drop: [ ALL ]

          # resources:
          #   limits:
          #     memory: 1Gi
          #     cpu: 500m
          #   requests:
          #     memory: 500Mi
          #     cpu: 100m

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              readOnly: false
            # - name: files
            #   subPath: run.sh
            #   mountPath: /opt/bitnami/scripts/postgresql/run.sh
            #   readOnly: true
            - name: secrets
              mountPath: /secrets/
              readOnly: true
            - name: tmp-files
              mountPath: /tmp
              readOnly: false
            - name: tmp-conf-files
              mountPath: /opt/bitnami/postgresql/conf
              readOnly: false

          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP

          env:
            - name:  POSTGRESQL_DATABASE
              value: gitlab
            - name:  POSTGRESQL_USERNAME
              value: gitlab
            - name:  POSTGRESQL_PASSWORD_FILE
              value: /secrets/database-password

      restartPolicy: Always

      volumes:
        - name: files
          configMap:
            name: files
        - name: data
          persistentVolumeClaim:
            claimName: database.data
        - name: secrets
          secret:
            secretName: secrets
            items:
              - key:  database-password
                path: database-password
        - name: tmp-files
          emptyDir: {}
        - name: tmp-conf-files
          emptyDir: {}
```

**Describe the results you received:**

Container exists with exit code 1.

**Describe the results you expected:**

Container starts properly, pod is not re-scheduled.

## Solution

Simple:

```diff
- is_postgresql_running && return
+ if is_postgresql_running; then
+   return 0
+ fi
```

Because `set -o errexit` is **not** evaluated in some case, like if statements, using it yields perfectly fine behavior under all circumstances. I can provide a PR if you'd like.

**Version**

K3s 1.21.0
PostgreSQL 13.3.0

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Not happening locally. I am running the cluster in a VM. Maybe a race-condition because the VM is slower and the PID file is not yet created when `get_pid_from_file "$POSTGRESQL_PID_FILE"` tries to obtain the PID.
