### ISSUE TITLE
Posrgres-HA customuser How do I get permission to create a user

### ISSUE THREAD

**Issue by NataShare** [bitnami/bitnami-docker-postgresql#306]
```yaml 
  postgresql:
    username: customuser
    password: custompassword
    database: customdatabase
    repmgrUsername: repmgruser
    repmgrPassword: repmgrpassword
    repmgrDatabase: repmgrdatabase
```
