### ISSUE TITLE
Changing the user id is not working

### ISSUE THREAD

**Issue by rizerzero** [bitnami/bitnami-docker-postgresql#321]
**Description**
Hello all, 
My current user id is 1002, I changed that in my docker-compose file, but some files have permissions issues 
```
test-database | /opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/postgresql/conf/pg_hba.conf: Permission denied
test-database | /opt/bitnami/scripts/libpostgresql.sh: line 222: /opt/bitnami/postgresql/conf/pg_hba.conf: Permission denied
```
**Steps to reproduce the issue:**

1. have a user with an id different than 1001
2. configure a docker-compose file to run with that id
3. create bind mount ```./volumes/database``` folder  for the database files with that same user 
4. run the docker-compose file 

**Describe the results you received:**
```
Creating network "database" with the default driver
Creating test-database ... done
Attaching to test-database
test-database | postgresql 09:56:56.43
test-database | postgresql 09:56:56.43 Welcome to the Bitnami postgresql container
test-database | postgresql 09:56:56.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
test-database | postgresql 09:56:56.44 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
test-database | postgresql 09:56:56.44
test-database | postgresql 09:56:56.45 INFO  ==> ** Starting PostgreSQL setup **
test-database | postgresql 09:56:56.48 INFO  ==> Validating settings in POSTGRESQL_* env vars..
test-database | postgresql 09:56:56.49 INFO  ==> Loading custom pre-init scripts...
test-database | postgresql 09:56:56.49 INFO  ==> Initializing PostgreSQL database...
test-database | postgresql 09:56:56.51 INFO  ==> pg_hba.conf file not detected. Generating it...
test-database | postgresql 09:56:56.51 INFO  ==> Generating local authentication configuration
test-database | /opt/bitnami/scripts/libpostgresql.sh: line 222: /opt/bitnami/postgresql/conf/pg_hba.conf: Permission denied
test-database | postgresql 09:56:56.52 INFO  ==> Deploying PostgreSQL with persisted data...
test-database | /opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/postgresql/conf/pg_hba.conf: Permission denied
```
**Describe the results you expected:**
Expecting all files to have the correct permissions 

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

```yaml
version: '2.4'

services:
# ==============================================================================
# Database services
# ==============================================================================

  database:
    image: bitnami/postgresql:14.1.0
    user: "1002:1002"
    volumes:
      - ./volumes/database:/bitnami/postgresql
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_ROOT_PASSWORD : test
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - database

networks:
  database:
    name: database
```
I recently started using Bitnami images, thank you for the great images you're providing us. 

Update : 

I have found a solution on StackOverflow which consists of setting up the root GID 
```    user: "1002:0" ```
I don't feel it's the right way to do it. 
It seems like even if I'm the user 1001, if configure the UID and GID it will fail to start with the permissions error?
