### ISSUE TITLE
Custom pg_hba.conf file messes up the database setup

### ISSUE THREAD

**Issue by biguphpc** [bitnami/bitnami-docker-postgresql#333]
### Name and Version

bitnami/postgresql:12-debian-10

### What steps will reproduce the bug?

1. Create a docker-compose file like so
```
version: '3'
services:
  pg-tooling-master: &pg-tooling
    build: .
    container_name: postgres-tooling-master
    hostname: pg-tooling-master
    restart: unless-stopped
    network_mode: bridge
    shm_size: '4gb'
    ports:
      - "5432:5432"
    volumes:
      - pg-tooling-master-data:/bitnami/postgresql
    environment:
      TZ: "America/Chicago"
      PGTZ: "America/Chicago"
      POSTGRESQL_DATA_DIR: "/bitnami/postgresql/data"
      POSTGRESQL_PASSWORD: postgres42
      POSTGRESQL_POSTGRES_PASSWORD: postgres42
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: postgres_repl
      POSTGRESQL_REPLICATION_PASSWORD: postgres42

volumes:
  pg-tooling-master-data:
```
2. Create a Dockerfile like so:
```
FROM bitnami/postgresql:12-debian-10
USER root
COPY configuration/ /bitnami/postgresql/conf/
USER 1001
WORKDIR /bitnami/postgresql
```
3. Create a directory structure like so (can use empty files to test this bug)
![image](https://user-images.githubusercontent.com/2192458/158471038-64caf0f8-3fe6-46d6-bde9-82cf0e6a731d.png)

4. run `docker-compose up --build pg-tooling-master` 

### What is the expected behavior?

When using a custom `pg_hba.conf` file, the server stops after stating `Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected`:
```postgres-tooling-master | postgresql 15:45:44.38 INFO  ==> ** Starting PostgreSQL setup **
postgres-tooling-master | postgresql 15:45:44.39 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgres-tooling-master | postgresql 15:45:44.40 INFO  ==> Loading custom pre-init scripts...
postgres-tooling-master | postgresql 15:45:44.40 INFO  ==> Initializing PostgreSQL database...
postgres-tooling-master | postgresql 15:45:44.40 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgres-tooling-master | postgresql 15:45:45.39 INFO  ==> Starting PostgreSQL in background...
postgres-tooling-master | postgresql 15:45:45.74 INFO  ==> Changing password of postgres
postgres-tooling-master | postgresql 15:45:45.78 INFO  ==> Stopping PostgreSQL...
```
**Note** the server stops after **Changing password of postgres**

When I try to connect I get:
```
postgres-tooling-master | 2022-03-15 15:40:26.297 CDT [75] FATAL:  password authentication failed for user "postgres"
postgres-tooling-master | 2022-03-15 15:40:26.297 CDT [75] DETAIL:  User "postgres" has no password assigned.
postgres-tooling-master |       Connection matched pg_hba.conf line 1: "host        all             all     0.0.0.0/0       md5"
```
probably because the server did not finish it's configuration

When the _pg_hba.conf_ is not provided in the configuration (comment `COPY configuration/ /bitnami/postgresql/conf/` in `Dockerfile`) then the server finishes the configuration properly:
```
postgres-tooling-master | postgresql 15:42:46.87 INFO  ==> ** Starting PostgreSQL setup **
postgres-tooling-master | postgresql 15:42:46.88 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgres-tooling-master | postgresql 15:42:46.89 INFO  ==> Loading custom pre-init scripts...
postgres-tooling-master | postgresql 15:42:46.89 INFO  ==> Initializing PostgreSQL database...
postgres-tooling-master | postgresql 15:42:46.91 INFO  ==> pg_hba.conf file not detected. Generating it...
postgres-tooling-master | postgresql 15:42:46.91 INFO  ==> Generating local authentication configuration
postgres-tooling-master | postgresql 15:42:47.89 INFO  ==> Starting PostgreSQL in background...
postgres-tooling-master | postgresql 15:42:48.26 INFO  ==> Changing password of postgres
postgres-tooling-master | postgresql 15:42:48.31 INFO  ==> Creating replication user postgres_repl
postgres-tooling-master | postgresql 15:42:48.35 INFO  ==> Configuring replication parameters
postgres-tooling-master | postgresql 15:42:48.39 INFO  ==> Configuring fsync
postgres-tooling-master | postgresql 15:42:48.41 INFO  ==> Loading custom scripts...
postgres-tooling-master | postgresql 15:42:48.42 INFO  ==> Enabling remote connections
postgres-tooling-master | postgresql 15:42:48.45 INFO  ==> Stopping PostgreSQL...
postgres-tooling-master | postgresql 15:42:49.47 INFO  ==> ** PostgreSQL setup finished! **
postgres-tooling-master | 
postgres-tooling-master | postgresql 15:42:49.52 INFO  ==> ** Starting PostgreSQL **
postgres-tooling-master | 2022-03-15 15:42:49.543 CDT [1] LOG:  starting PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
```

Can you fix this ? It's important we can both provide a custom _pg_hba.conf_ and have the server setup correctly

### What do you see instead?

The servers stops after stating `Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected`
