### ISSUE TITLE
docker stack support ?

### ISSUE THREAD

**Issue by kevin71020** [bitnami/bitnami-docker-postgresql#75]
Change docker compose to 3.0 and run docker stack  in swarm mode. Docker stack file to create Postgresql master/slave setup with 2 slaves.

The slave container will restart in few minutes repeat and repeat....

Does bitnami-docker-postgresql support docker stack  ?

`docker stack deploy -c docker-stack-postgresql.yml post`

docker-stack-postgresql.yml  :
```
version: "3"
services:
  db1:
    image: bitnami/postgresql:latest
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - awesomenet
    deploy:
      placement:
        constraints: [node.hostname == node-docker-1]
    volumes:
      - pgdata:/bitnami/postgresql
    env_file: .env.master
  db2:
    image: bitnami/postgresql:latest
    depends_on:
      - db1
    ports:
     - "127.0.0.1:5433:5432"
    networks:
      - awesomenet
    deploy:
      placement:
        constraints: [node.hostname == node-docker-2]
    volumes:
      - pgdata:/bitnami/postgresql
    env_file: .env.slave
  db3:
    image: bitnami/postgresql:latest
    depends_on:
      - db1
    ports:
      - "127.0.0.1:5434:5432"
    networks:
      - awesomenet
    deploy:
      placement:
        constraints: [node.hostname == node-docker-3]
    volumes:
      - pgdata:/bitnami/postgresql
    env_file: .env.slave
volumes:
  pgdata:

networks:
  awesomenet:
    driver: overlay
    driver_opts:
      encrypted: "true"
   
```
.env.master
```
POSTGRESQL_REPLICATION_MODE=master
POSTGRESQL_REPLICATION_USER=replication_user
POSTGRESQL_REPLICATION_PASSWORD= replication_password
POSTGRESQL_USERNAME=postgres
POSTGRESQL_PASSWORD=password
POSTGRESQL_DATABASE=monkey_db
```
.env.slave
```
POSTGRESQL_REPLICATION_MODE=slave
POSTGRESQL_REPLICATION_USER=replication_user
POSTGRESQL_REPLICATION_PASSWORD=b1uxcdq
POSTGRESQL_MASTER_HOST=db1
POSTGRESQL_MASTER_PORT=5432
```
**Describe the results you received:**
Slave PostgreSQL container repeat restart. The container ID d0d524efef3b and fc2dad909a8d is different.
 ```
root@prod-mongocfg-3:~# docker container ls
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS               NAMES
d0d524efef3b        bitnami/postgresql:latest   "/app-entrypoint.sh …"   10 seconds ago      Up 3 seconds        5432/tcp            post_db3.1.jooxfzvu79hcxlmb5sn8uog8n
754e313f60c3        mongo:3.4                   "docker-entrypoint.s…"   15 hours ago        Up 15 hours         27017/tcp           mongo_cfg3.1.pspq5zaofb6szowigc90mzlzb
root@prod-mongocfg-3:~# docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
754e313f60c3        mongo:3.4           "docker-entrypoint.s…"   15 hours ago        Up 15 hours         27017/tcp           mongo_cfg3.1.pspq5zaofb6szowigc90mzlzb
root@prod-mongocfg-3:~# docker container ls
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS               NAMES
fc2dad909a8d        bitnami/postgresql:latest   "/app-entrypoint.sh …"   10 seconds ago      Up 3 seconds        5432/tcp            post_db3.1.z00tj2xtohnfq7nzo7ed9gma3
754e313f60c3        mongo:3.4                   "docker-entrypoint.s…"   15 hours ago        Up 15 hours         27017/tcp           mongo_cfg3.1.pspq5zaofb6szowigc90mzlzb
root@prod-mongocfg-3:~#
```
**Describe the results you expected:**
the container 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 4
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: z1vuhr78a3ic7gp1j20dfdjhg
 Is Manager: false
 Node Address: 10.130.26.240
 Manager Addresses:
  10.130.14.137:2377
  10.130.50.166:2377
  10.130.51.8:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.3MiB
Name: prod-mongocfg-3
ID: 3QFN:JL77:SHGU:5WXO:GYUK:BWK2:QQQ7:RPER:JE7L:JMFN:MHOJ:SX26
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
The program 'docker-compose' is currently not installed. You can install it by typing:
apt install docker-compose
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Digitalocean

**Comment by kevin71020** [comment]
PostgreSQL slave con not set volume and everything go well !

```
version: "3"
services:
  db1:
    image: bitnami/postgresql:latest
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - awesomenet
    deploy:
      placement:
        constraints: [node.hostname == node-docker-1]
    volumes:
      - pgdata:/bitnami/postgresql
    env_file: .env.master
  db2:
    image: bitnami/postgresql:latest
    depends_on:
      - db1
    ports:
     - "127.0.0.1:5433:5432"
    networks:
      - awesomenet
    deploy:
      placement:
        constraints: [node.hostname == node-docker-2]
    env_file: .env.slave
  db3:
    image: bitnami/postgresql:latest
    depends_on:
      - db1
    ports:
      - "127.0.0.1:5434:5432"
    networks:
      - awesomenet
    deploy:
      placement:
        constraints: [node.hostname == node-docker-3]
    env_file: .env.slave
volumes:
  pgdata:
```
