### ISSUE TITLE
Postgresql master does not pick up configuration from file

### ISSUE THREAD

**Issue by rvit34** [bitnami/bitnami-docker-postgresql#80]
**Description**

Postgresql master server that is launched within docker does not pick up configuration properties from file.

**Steps to reproduce the issue:**

0. Prepare configuration file and place it to `./postgresql/postgresql_master_data/conf/` directory. I have the next content of this file:
```
log_directory = 'pg_log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_statement = 'all'
logging_collector = on
```
1. run `docker-compose up -d`
```
version: '2'

services:

  db-master:
    image: 'bitnami/postgresql:9.6'
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/postgresql_master_data/conf/postgresql.conf:/bitnami/postgresql/conf/postgresql.conf
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=slave
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=test_db

  db-slave:
    image: 'bitnami/postgresql:9.6'
    ports:
      - '5433:5432'
    depends_on:
      - db-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=slave
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_MASTER_HOST=db-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
```
2. Check the logs from the container with master-db:

```
Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected configuration files found. Creating default config file... // <----
postgre INFO  ==> Deploying PostgreSQL from scratch...
postgre INFO  ==> Creating database solidopinion...
postgre INFO  ==> Creating postgres user with unrestricted access...
postgre INFO  ==> Creating replication user solidopinion...
postgre INFO  ==> Configuring PostgreSQL...
postgre INFO  ==> Configuring replication parameters...
postgre INFO  ==> Configuring permissions for config files...
....

```
3. Get shell into container and check that file `postgresql.conf` is presented at `bitnami/postgresql/conf` directory.

```
docker-compose exec db-master bash
root@fa47b0939cfa:/# cat /bitnami/postgresql/conf/postgresql.conf
log_directory = 'pg_log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_statement = 'all'
logging_collector = on
root@fa47b0939cfa:/# 
```

**Describe the results you received:**

Injected default configuration.

**Describe the results you expected:**

Injected provided configuration.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false

```

- Output of `docker-compose version`:

```
docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```
