### ISSUE TITLE
Connection hangs in a replication setup after some idle time

### ISSUE THREAD

**Issue by airstofather** [bitnami/bitnami-docker-postgresql#83]
**Description**

After establishing a connection to the primary server and some idle time (about 10 minutes) the connection seems to go in the lala land. It doesn't close due to timeout but it also doesn't work. Sending a query results in a hung terminal.

I am using a docker swarm setup to deploy (in this case) one primary and one replica. Everything seems to work fine in the beginning. My real setup involves a rails app with unicorn and nginx, but I was able to isolate the issue to the postgres image.

**Steps to reproduce the issue:**

1. Use the following `stack` file and `environment.env` to deploy a stack on two swarm nodes:

stack.yml:
```
version: "3.3"

networks:
  test_net:
    external: true

volumes:
  pg-primary-vol:
  pg-replica-vol:

services:

  pg-primary:
    image: "bitnami/postgresql:9.6"
    env_file: environment.env
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
    volumes:
      - type: volume
        source: pg-primary-vol
        target: /bitnami
    networks:
      - test_net
    deploy:
      placement:
        constraints:
          - node.labels.data_center == dc-02

  pg-replica:
    image: "bitnami/postgresql:9.6"
    env_file: environment.env
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=pg-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - type: volume
        source: pg-replica-vol
        target: /bitnami
    networks:
      - test_net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.data_center == dc-03
```
environment.env
```
POSTGRESQL_USERNAME=some_user
POSTGRESQL_PASSWORD=somePassword
POSTGRESQL_DATABASE=some_name_db
POSTGRESQL_REPLICATION_USER=another_user
POSTGRESQL_REPLICATION_PASSWORD=anotherPassword
```
2. Deploy the stack: `docker stack deploy -c stack.yml dbserver`
3. After deployment I have the primary container running on node with label data_center == 02 and a secondary on the data_center == 03. All is well so far. I then get on the node with the secondary and use `psql` to connect to the primary like so:
```
psql -U some_user -h dbserver_pg-primary some_name_db
```
 4. After this I try to list the tables which displays the expected `No relations found`.
 5. Wait 10 minutes and run `\dt` again

**Describe the results you received:**

Nothing, no results. psql just hangs and I have to CTRL+Z to quit it. What's interesting is that if I reconnect to the database again everything works fine until the next window of 10 minutes or so of idle time.

**Describe the results you expected:**

Expecting the idle connection to stay alive

**Additional information you deem important (e.g. issue happens only occasionally):**

If I connect from the same container were the primary is running I don't see this issue. Something is going on with the network connection but I don't know what. 

I'd be very grateful if someone can point out where the issue is coming from (my host, my docker stack configuration, the image etc) and how to fix this.

**Version**

- Output of `docker version`:

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 56
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: iglb3ep6dysyzvo2jyv8vy0tq
 Is Manager: false
 Node Address: x.x.x.x
 Manager Addresses:
  x.x.x.x:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-121-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 987.4MiB
Name: toybox-01
ID: PQCV:AGUG:HYLR:MRTI:C2FM:MEYC:5KVO:QPBE:RLU4:TTJA:FNDT:3TVH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
N/A
```
