### ISSUE TITLE
Question - about image

### ISSUE THREAD

**Issue by stephenmoloney** [bitnami/bitnami-docker-postgresql#99]
I'm trying to figure out where the code is that shows the user and database ***being created*** not just connecting.

Can't find code showing the creation of a user based on ```POSTGRESQL_USERNAME```

Can someone point me in the right direction ?

**Comment by juan131** [comment]
Hi @stephenmoloney 

The logic that initialise PostgreSQL is included in the Nami module (which is the package that contains both PostgreSQL binaries and the scripts to initialise it). That Nami module is downloaded as shown in the line below of the Dockerfile:

https://github.com/bitnami/bitnami-docker-postgresql/blob/master/10/debian-9/Dockerfile#L9

We're currently moving this approach to bash scripts that are more open and easy to understand for user. E.g. [MySQL container](https://github.com/bitnami/bitnami-docker-mysql)
As you can check the logic to initialise MySQL is written in Bash: https://github.com/bitnami/bitnami-docker-mysql/tree/master/8.0/debian-9/rootfs

We'll move PostgreSQL to this approach very soon.

On the other hand, by setting the env. variable **NAMI_DEBUG** to the value **--log-level=trace** you'll increase the logs verbosity. E.g. (docker-compose)

```
version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - NAMI_DEBUG='--log-level=trace'
```
